node AngGenScr TABLES=EPM_STEPS,CEP_JOINS_DEF BASE=output/ MODULE=epm/ TYPE=FORM_GRID KEYS=FLOW_CODE SCREEN=epm_steps_lookup
node AngGenScr TABLES=STM_CDR_DEF,STM_MODULE_DATA BASE=output/ MODULE=epm/ TYPE=FORM_GRID KEYS=CDR_TYPE SCREEN=epm_cdr_data
node AngGenScr TABLES=EIM_COMMANDS,EIM_COMMANDS BASE=output/ MODULE=eim/ TYPE=FORM_GRID KEYS=SPC_FUNCTION SCREEN=eim_test_format
node AngGenScr TABLES=EPM_STEPS,LGC_HEAD BASE=output/ MODULE=epm/ TYPE=FORM_GRID KEYS=FLOW_CODE SCREEN=epm_steps_rules
node AngGenScr TABLES=EIM_COMMAND_RECORD,EIM_EXECUTED_COMMANDS BASE=output/ MODULE=eim/ TYPE=FORM_GRID KEYS=TRANSNO SCREEN=eim_test_switch
node AngGenScr TABLES=ADM_USER_INFORMATION,ADM_AUTHORITY BASE=output/ MODULE=adm/ TYPE=FORM_GRID KEYS=USERNAME SCREEN=adm_users
node AngGenScr TABLES=MENUS,ROUTINES BASE=output/ MODULE=adm/ TYPE=FORM_GRID KEYS=CHOICE SCREEN=adm_menus
